# Generated by Django 2.0.2 on 2018-03-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichsandwich', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='whichsandwich.Sandwich'),
        ),
    ]
