# Generated by Django 2.0.2 on 2018-03-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whichsandwich', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sandwich',
            options={'verbose_name_plural': 'Sandwiches'},
        ),
    ]
