# Generated by Django 2.0.2 on 2018-03-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichsandwich', '0002_auto_20180309_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
